### PR TITLE
Add functionality to scroll text

### LINKED ISSUE #4: Scrolling Text
Given a line of text I would like to have it scroll across the matrix.

### PR DESCRIPTION
**Pull request by ThauEx**
Resolves #4

### CODE REVIEW

**Comment by adkron** [comment]
Thanks! I don't have anything with me to test this but everything looks good to me. I'd love the mono spaced work you put in to be exposed. Think the scroll text could take in an optional monos paced param?

The work you put into creating a font is awesome. Thanks.

**Comment by ThauEx** [comment]
Thanks ;)
I took the font from https://xantorohara.github.io/led-matrix-editor, maybe I should credit it somewhere.
Yes, I will add this option, monospaced scrolling text is not that nice, because it's quite hard to read. But to have it optional should be fine.

**Comment by adkron** [comment]
It would be great to credit the font in the top of the font file. The monospaced could be great if we could figure out how to scroll across more than one matrix. V2, right?

Amos King
Binary Noggin

**Comment by ThauEx** [comment]
I added the credits and the monospace option.

Yeah V2 :D

**Comment by adkron** [comment]
Great work. Thanks for taking the time to do this. I'm just merging even though I can't test right now. The code looks good and is small enough.

**Pull request merged**
